const test=require('node:test');
const assert=require('node:assert/strict');
global.getPlanning2DomainTargetMinutesPerWeek=employee=>employee.weekTarget;
global.getPlanning2DomainContractTargetMinutesPerMonth=employee=>employee.monthTarget;
const api=require('../planning2-manual-tools.js');

test('personal favorites use only real work patterns and rank frequency before recency',()=>{const shift=(start,end)=>({type:'shift',status:'work',start,end,minutes:300,pause:0});const schedule={'2026-08-01':{a:shift('09:00','14:00')},'2026-08-02':{a:{type:'vacation',status:'vacation'}},'2026-08-03':{a:shift('10:00','15:00')},'2026-08-04':{a:shift('09:00','14:00')},'2026-08-05':{a:{type:'external-help',externalHelp:true,start:'09:00',end:'14:00'}}};const result=api.getPlanning2PersonalShiftFavorites(schedule,'a',2);assert.equal(result.length,2);assert.equal(result[0].count,2);assert.equal(result[0].entry.start,'09:00');assert.notStrictEqual(result[0].entry,schedule['2026-08-04'].a)});

test('balance preview replaces an existing shift rather than adding the new effect',()=>{const current={schedule:{'2026-09-08':{a:{minutes:300}}}},next={schedule:{'2026-09-08':{a:{minutes:360}}}},employee={id:'a',weekTarget:1800,monthTarget:7800},resolve=(plan,emp,iso)=>({minutesForMonth:plan.schedule[iso]?.[emp.id]?.minutes||0});const result=api.getPlanning2ManualBalancePreview({currentPlan:current,nextPlan:next,employee,isoDate:'2026-09-08',resolve});assert.equal(result.weekAfter-result.weekBefore,60);assert.equal(result.monthAfter-result.monthBefore,60)});

test('editor warning selects one cell/day warning with carryover priority',()=>{const warnings=[{kind:'free-day',employeeId:'a'},{kind:'coverage',isoDate:'2026-09-08',source:{gaps:[{kind:'closing'}]}},{kind:'carryover',isoDate:'2026-09-08'}];assert.equal(api.getPlanning2EditorWarning(warnings,'2026-09-08','a'),'Öffner am Folgetag prüfen');assert.equal(api.getPlanning2EditorWarning([{kind:'coverage',isoDate:'2026-09-08',source:{gaps:[{kind:'closing'}]}}],'2026-09-08','a'),'Zweiter Schließer fehlt')});

test('copy and multi templates accept only genuine work shifts',()=>{assert.equal(api.isPlanning2ManualWorkShift({type:'shift',status:'work'}),true);assert.equal(api.isPlanning2ManualWorkShift({type:'shift',status:'vacation'}),false);assert.equal(api.isPlanning2ManualWorkShift({type:'external-help',status:'external'}),false)});

test('manual shift path accepts entries from every central work-shift builder',()=>{const fs=require('node:fs'),vm=require('node:vm'),context={};vm.createContext(context);for(const file of ['time-utils.js','shift-rules.js','shift-utils.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});const entries=[context.buildEarlyShiftEntry('F5'),context.buildLateShiftEntryForWorkedMinutes(300,false),context.buildFullShiftEntry(false),context.buildWorkDurationShiftEntry('09:00',300)];for(const entry of entries){assert.equal(entry.status,'shift');assert.equal(api.isPlanning2ManualWorkShift(entry),true);assert.ok(api.createPlanning2ManualShiftTemplate(entry))}});

test('manual shift path still rejects external help and non-work day types',()=>{for(const entry of [{type:'external-help',status:'external',externalHelp:true},{type:'vacation',status:'vacation'},{type:'sick',status:'sick'},{type:'off',status:'off'}])assert.equal(api.isPlanning2ManualWorkShift(entry),false)});

test('F5 and L5 quick actions insert central shifts while G and Flex only switch editor mode',()=>{const fs=require('node:fs'),vm=require('node:vm'),live=fs.readFileSync('planning2-live.js','utf8'),start=live.indexOf('function applyQuick(');let depth=0,end=-1;for(let index=live.indexOf('{',start);index<live.length;index+=1){if(live[index]==='{')depth+=1;else if(live[index]==='}'&&--depth===0){end=index+1;break}}const elements={editType:{value:''}},plan={schedule:{}},inserted=[],synced=[],infoUpdates=[];const context={editing:{plan,eid:'a',dayIso:'2026-09-09'},document:{getElementById:id=>elements[id]},getTestPlan:()=>plan,applyPlanning2ManualShift:(target,eid,dayIso,entry)=>{inserted.push({target,eid,dayIso,entry});target.schedule[dayIso]={[eid]:entry};return{ok:true}},persist:()=>{},getPlanning2LastWorkShift:()=>null,putEntry:()=>{},syncEditorFields:kind=>synced.push(kind),updatePlanning2EditorInfo:()=>infoUpdates.push(true)};vm.createContext(context);for(const file of ['time-utils.js','shift-rules.js','shift-utils.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});vm.runInContext(`${live.slice(start,end)};this.applyQuick=applyQuick`,context);context.applyQuick('F5');context.applyQuick('L5');assert.deepEqual(inserted.map(item=>item.entry.code),['F5','L5']);assert.deepEqual(inserted.map(item=>item.entry.status),['shift','shift']);context.applyQuick('G');assert.equal(elements.editType.value,'G');context.applyQuick('FLEX');assert.equal(elements.editType.value,'FLEX');assert.deepEqual(synced,['G','FLEX']);assert.equal(infoUpdates.length,2);assert.equal(inserted.length,2)});

test('copied automatic 19:10/carryover shift becomes a clean manual template',()=>{const source={type:'shift',status:'work',code:'G',shiftKey:'G',mode:'full',shiftType:'full',start:'09:00',end:'19:10',minutes:555,pause:15,planning2AutoCloser:true,planning2AutoOpener:true,planning2Carryover:{from:'x'},changedAt:'x'};const template=api.createPlanning2ManualShiftTemplate(source,(base,start,end)=>({...base,start,end,pause:30,breakMinutes:30,minutes:550,withCheckout:end==='19:10'}));assert.equal(template.end,'19:10');assert.equal(template.withCheckout,true);assert.equal(template.minutes,550);assert.equal(template.planning2AutoCloser,undefined);assert.equal(template.planning2AutoOpener,undefined);assert.equal(template.planning2Carryover,undefined);assert.equal(template.changedAt,undefined)});

test('favorite entries are clean templates without transient automation metadata',()=>{const schedule={'2026-09-01':{a:{type:'shift',status:'work',code:'FLEX',start:'08:55',end:'14:55',minutes:360,planning2AutoOpener:true,internalDebug:'x'}}};const favorite=api.getPlanning2PersonalShiftFavorites(schedule,'a',1)[0].entry;assert.equal(favorite.start,'08:55');assert.equal(favorite.planning2AutoOpener,undefined);assert.equal(favorite.internalDebug,undefined)});

test('live multi-plan delegates to the shared manual shift path with empty-cell protection',()=>{const source=require('node:fs').readFileSync(require('node:path').join(__dirname,'..','planning2-live.js'),'utf8');assert.match(source,/function applyPlanning2ManualShift[^]*?requireEmpty[^]*?resolved\.status!==\'empty\'/);assert.match(source,/function applyPlanning2MultiCell[^]*?applyPlanning2ManualShift\([^]*?requireEmpty:true/);assert.match(source,/function applyQuick[^]*?applyPlanning2ManualShift/);assert.doesNotMatch(source,/function applyPlanning2MultiCell[^}]*?putEntry\(/)});
